services:
  db:
    image: postgres:15
    env_file:
      - .env
    container_name: teamfinder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    env_file:
      - .env
    container_name: teamfinder_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  media_volume:
